vpc:
  cidrBlock: "10.0.0.0/16"
  subnetCidrBlock: "10.0.1.0/24"
  availabilityZone: "us-west-2a"
  tags:
    Name: "my-vpc"
    SubnetName: "my-public-subnet"
    InternetGatewayName: "my-igw"
    RouteTableName: "my-route-table"