name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

env:
  WORKING_DIRECTORY: ./iac
  REGION: us-east-1
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18    

      - name: Install Dependencies
        run: npm install

      - name: Install pulumi
        uses: pulumi/actions@v4

      - name: Setup pulumi
        run: |
          pulumi login ${{ var.PULUMI_STATE_LOCATION }}
          pulumi stack ls
          pulumi stack select dev --non-interactive

      # - uses: pulumi/actions@v5
      #   env:
      #     PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ env.REGION }}
      #   with:
      #     command: preview
      #     stack-name: dev
      #     cloud-url: s3://pulumi-state-bucket-04040527


    #  - name: Update .env
    #   run: |
        
      # working-directory: ${{ env.WORKING_DIRECTORY }}
      # shell: bash

    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     run: aws ecr get-login-password --region <your-aws-region> | docker login --username AWS --password-stdin <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com

    #   - name: Build Docker image
    #     run: docker build -t <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com/<repository-name>:latest .
      
    #   - name: Push Docker image to Amazon ECR
    #     run: docker push <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com/<repository-name>:latest